language: python
sudo: required
dist: xenial
cache: pip
python: "3.7"
install:
  - pip install -r requirements_dev.txt
script:
  - python -m pytest --cov=rl tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
